### ISSUE TITLE
Loading Trained Models

### ISSUE THREAD

**Issue by ItamarSafriel** [facebookresearch/vissl#235]
Hello, 
I followed the given tutorials and manged to train a model on a custom dataset. 
The training seemed to work but I can't figure out how to use the trained model. 
I tried building the model as follows:  
```python
import yaml
from vissl.utils.hydra_config import AttrDict
cfg = yaml.load(open("path_to_config_yaml"), loaded=yaml.FullLoader)["config"]
cfg = AttrDict(cfg)

from vissl.model import build_model 
model = build_model(cfg.MODL, cfg.OPTIMIZER)
```
Where ```path_to_config_yaml``` is the path to the same config as the one used in training (```configs/config/quick_1gpu_resnet50_simclr.yaml```). 
 The following error accord: 
```
AttributeError: AttrDict object has no attribute FEATURE_EVAL_SETTINGS.
``` 
Any ideas on how to solve this? Otherwise, is there a tutorial which explains how to load trained models? I have read [How to Load Pretrained Models](https://vissl.readthedocs.io/en/latest/evaluations/load_models.html) but couldn't really understand.  

If more information is needed, please comment and I'll provide it
Thanks!

**Comment by prigoyal** [comment]
Thank you for reaching out. You can refer to tutorials https://colab.research.google.com/drive/1m1LUa-3vIR-rxwcm0QCrefc5S6PAY874?usp=sharing for example on how we load torchvision resnet model.

For the error that you mention , it seems like the config file is not loaded/parsed correctly. Can you try the VISSL provided function https://github.com/facebookresearch/vissl/blob/master/vissl/utils/hydra_config.py#L89 ? Otherwise can you share what the output of `print(cfg.MODEL)` in your case looks like?

**Comment by ItamarSafriel** [comment]
Hello, Thank you very much for your response. 
It seems like the colab notebook you linked is loading model weights for finetuing. This is not what I am looking for. 
I want to know how to load a model I trained and use it for inference. I need something as follows: 
```python
model = troch.load("path_to_some_model") 
image = plt.imread("path_to_some_image")
pred = model(image)
```
So after I trained a SimCLR on a custom dataset, how do I use the trained model for inference? 

Regarding the function ```convert_to_attrdict```, I tried using it as follows: 
```python 
import yaml
from vissl.utils.hydra_config import AttrDict, convert_to_attrdict

cfg = yaml.load(open("/content/configs/config/quick_1gpu_resnet50_simclr.yaml"), Loader=yaml.FullLoader)["config"]
cfg = convert_to_attrdict(cfg)
```
And I got this error: 
```python
--> 440         assert isinstance(cfg, Container)
    441         # noinspection PyProtectedMember
    442         return BaseContainer._to_content(cfg, resolve=resolve, enum_to_str=enum_to_str)

AssertionError:
```
The print I get from ```python print(cfg.MODEL)``` is:

```json 
{
   "TRUNK":{
      "NAME":"resnet",
      "RESNETS":{
         "DEPTH":50
      }
   },
   "HEAD":{
      "PARAMS":[
         [
            "mlp",
            {
               "dims":[
                  2048,
                  2048
               ],
               "use_relu":true
            }
         ],
         [
            "mlp",
            {
               "dims":[
                  2048,
                  128
               ]
            }
         ]
      ]
   },
   "SYNC_BN_CONFIG":{
      "CONVERT_BN_TO_SYNC_BN":true,
      "SYNC_BN_TYPE":"pytorch"
   },
   "AMP_PARAMS":{
      "USE_AMP":false,
      "AMP_ARGS":{
         "opt_level":"O3",
         "keep_batchnorm_fp32":true,
         "master_weights":true,
         "loss_scale":"dynamic"
      }
   }
}
```
After loading it as mentioned in my original question. 
Any Ideas? 
Thank you very much!!

**Comment by prigoyal** [comment]
thank you for sharing the info above. I think we should try to figure out why the `convert_to_attrdict` doesn't work for you. Can you try following https://github.com/facebookresearch/vissl/blob/master/tools/run_distributed_engines.py#L31-L33 for loading a config file? we use hydra for our config management and have neither tried simple `yaml.load` nor is supported.

**Comment by ItamarSafriel** [comment]
Hey, 
I manged to make it work and use my trained model for inference. 
The problem was with my config file. I was missing values because it was the wrong config for the task. 
Thank very much for your help. 

If I may, I would suggest converting the way models are used and loaded to a more "detectron2ish" way. I think it's very intuitive and will help new users. I would also consider rewriting some of the README files, they do not give enough emphasis on the fact that the config files are the ones which determine what ```run_distributed_engines.py``` would do. I thought They were only used for training and it took me some time to understand they are used for inference as well. 

I do not have a lot of experience with any of the things I mentioned above, but if I can contribute in any way, I'd love to try. 

Thanks again for the help!

**Comment by prigoyal** [comment]
Hi @ItamarSafriel , really awesome to hear that.

Thank you also for your feedback on the readme files. Please go ahead and propose a PR. It will certainly help more users as well :)

For the loading of model in "detectron2ish" way, can you share what the difference is currently with VISSL loading and what  is the part that's inconvenient? I do think think that we should to improve this if there's an opportunity :)

**Comment by glebss** [comment]
Hi @prigoyal, thanks a lot for awesome job and repository! 
Following your discussion and advises I was able to build the model. Several additions to config file were necessary as well. Nevertheless, I have difficulties with loading pre-trained weights from the checkpoint. As far as I understand from the final part of [this tutorial](https://colab.research.google.com/drive/1m1LUa-3vIR-rxwcm0QCrefc5S6PAY874?usp=sharing#scrollTo=9xFUcTj00B_a) model's `state_dict` is located under `classy_state_dict` key. However when I try to load weights using classical torch functions, e.g.
```
weights = torch.load("weights_path")
model.load_state_dict(weights["classy_state_dict"])
```
I've got an error saying `Unexpected key(s) in state_dict: "train", "base_model", "meters", "optimizer", "phase_idx", "train_phase_idx", "num_updates", "losses", "hooks", "loss"`

So my questions are:
1. Is there any convenient way to load pre-trained weights?
2. What should I change in config, `build_model` function etc. to load only trunk weights? 

Thanks in advance!

**Comment by prigoyal** [comment]
Hi @glebss , thank you ! I'd recommend to follow our documentation https://vissl.readthedocs.io/en/latest/evaluations/load_models.html + the tutorial https://colab.research.google.com/drive/1m1LUa-3vIR-rxwcm0QCrefc5S6PAY874?usp=sharing#scrollTo=YaUMDwMdzYHN where we directly load a torchvision ResNet50 model (not trained by VISSL). Hope that helps.

**Comment by guan-ai** [comment]
@ItamarSafriel can you share more details about how you successfully load the model and did the inference? 

@prigoyal I think we do need a more clean and clear documentation on how to use the trained model to do inference. None of the "tutorials" you mentioned about feature extraction or doing inference are easy to follow. (And none of them works after I spent hours on them) Maybe the instructions are out of date. There are multiple versions of config files, and some are for training, some for eval with some customization. But there is lacking a single up-to-date, clear, step-by-step guide about how to use the trained models to extract features or do prediction with 1 image as input. Hope to see that soon. Thank you.

**Comment by prigoyal** [comment]
Hi @guan-ai , thank you and I really appreciate your feedback. For feature extraction, the tutorial is https://vissl.ai/tutorials/Feature_Extraction . Please note that VISSL is evolving and for that reason we have marked "stable" version of everything. Please consider using the stable version. 

We would also be able to help you further if you can share what doesn't work: can you open separate issues for the errors you are encountering and we can help then?

For step-by-step guide on feature extraction, please see https://vissl.readthedocs.io/en/latest/flowcharts/extract_workflow.html and https://vissl.readthedocs.io/en/latest/evaluations/feature_extraction.html

Beyond that , please let us know what parts are unclear or what would you like to see. We certainly look forward to improving VISSL docs and would appreciate more details from you. Thank you!

**Comment by ItamarSafriel** [comment]
Hey @prigoyal sorry for the late response. 

It seems that in order to train/inference a model you need to change a given config file. This is very counter-intuitive. When using detectron2 this is usually done as follows: 
```python
cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("<path_to_config>"))
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("<path_to_config>")
.
.
.
trainer = DefaultTrainer(cfg) 
trainer.resume_or_load(resume=False)
trainer.train()
```  
And then after the training is finished, you can just do:
```python
cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth")
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = <some threshold> 
predictor = DefaultPredictor(cfg)
```
This syntax is what makes detectron2 very easy to learn and use. I think VISSL should aim for this. 

I have never contributed to any open source projects, but if the syntax change is something you are open to and can provide some guidance I would love to help.

**Comment by deeptek012** [comment]
@prigoyal Thanks for your amazing work and clarifications. Let me share what I found when using the custom trained model, and hopefully that will help improving the project for the ease of use. 

1. I got the 'extract_resnet_in1k_8gpu' config from the tutorial, and added 
`FEATURE_EVAL_SETTINGS:
      EVAL_MODE_ON: True
      FREEZE_TRUNK_ONLY: True
      EXTRACT_TRUNK_FEATURES_ONLY: True
      SHOULD_FLATTEN_FEATS: False
`
under the 'MODEL' section. 

2. I registered my custom data folder inside configs/config/dataset_catalog.json. (The 'save_data' function under vissl.utils.io would give a wrong format to the dataset_catalog.json file, but if you just type it in there manually it would work). 
3. my script for feature extraction looks like this. It is the best guess I had from reading this tutorial. (https://vissl.readthedocs.io/en/latest/evaluations/feature_extraction.html)
`python tools/run_distributed_engines.py \
    hydra.verbose=true \
    config=extract_resnet_in1k_8gpu \
    +config/trunk_only=rn50_layers \
    config.DATA.TRAIN.DATASET_NAMES=[imagenet1k_folder] \
    config.DATA.TRAIN.DATA_SOURCES=[disk_folder] \
    config.DATA.TRAIN.DATA_PATHS=["/my/img/path"] \
    config.DATA.TEST.DATASET_NAMES=[imagenet1k_folder] \
    config.DATA.TEST.DATA_SOURCES=[disk_folder] \
    config.DATA.TEST.DATA_PATHS=["/my/img/path"] \
    config.DISTRIBUTED.NUM_NODES=1 \
    config.DISTRIBUTED.NUM_PROC_PER_NODE=1 \
    config.MODEL.WEIGHTS_INIT.PARAMS_FILE="./checkpoints/my_model.torch" \
    config.MODEL.WEIGHTS_INIT.APPEND_PREFIX="trunk.base_model._feature_blocks." \
    config.MODEL.WEIGHTS_INIT.STATE_DICT_KEY_NAME=""
`
Questions & problems. 
1. The above steps got vissl running on the feature extraction (although I'm not so sure). It always got killed because OOM error. Even I reduced my images to be only a few, it would run out of the 16GB memory on my machine.  The last part of the log looks like `INFO 2021-03-22 08:24:21,839 trainer_main.py: 367: Model set to eval mode during feature extraction...
/usr/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 23 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
Killed
`
The code can take a lot more images when training, and finish the long-lasting training job. On inference, I couldn't get it work on a few images. 

2. Is my feature extraction command even correct? If I ignore any of those config options
`config.DATA.TRAIN.DATASET_NAMES=[imagenet1k_folder] \
    config.DATA.TRAIN.DATA_SOURCES=[disk_folder] \
    config.DATA.TRAIN.DATA_PATHS=["/my/img/path"] \
    config.DATA.TEST.DATASET_NAMES=[imagenet1k_folder] \
    config.DATA.TEST.DATA_SOURCES=[disk_folder] \
    config.DATA.TEST.DATA_PATHS=["/my/img/path"] \` it would either say "training is done" or "data is not found", which is contradicting the "feature extraction tutorial". 

3. While understanding all the knobs in the config file and how to get things run is fun, there is lacking of a demo program about how to **load a model and extract feature from simply 1 image** . Like @ItamarSafriel mentioned in previous post, such demo is really really helpful for folks just got started. 

4. I also saw someone mentioned document clarity. I agree with that. The biggest problem I faced was that the tutorials are not self-contained, meaning that by following 1 tutorial you hardly get things work. When you look at other tutorials to put things together, it's not intuitive. 

For example, in this tutorial (https://vissl.readthedocs.io/en/latest/evaluations/feature_extraction.html), at least we can add how to set up your data folder and what to expect when you run that command of `python tools/run_distributed_engines.py \
    config=feature_extraction/extract_resnet_in1k_8gpu \
    +config/feature_extraction/trunk_only=rn50_layers \
    config.MODEL.WEIGHTS_INIT.PARAMS_FILE=<my_weights.torch>` In fact, this command doesn't work out of box. There are bits and pieces scattered in a few other places, and it's hard to put things together when you have combinations of choices. 

Again, thanks for the work and I believe it has great potential. That's why I'm trying to get it to work although as of now it is harder to use than many other popular options. Thanks for your work and I'm looking forward to your support.

**Comment by deeptek012** [comment]
@ItamarSafriel it seems you got the inference part working for the 1-image feature extraction? If so, would you please share that? Thanks!

**Comment by prigoyal** [comment]
thank you for the detailed feedback @deeptek012 and @ItamarSafriel . We will work on remediation and to start, it's clear that we need to provide a 1-stop-shop documentation for the use case that's common here in the thread (feature extraction, full finetuning). We will work on that as the immediate step.

**Comment by QuentinDuval** [comment]
Hi everyone,

I will try to provide here some basic recipes that will hopefully help dealing with loading models / using them for feature extractions / inference, which (if you find them useful) might end up in a documentation.

I will concentrate on loading a model pre-trained via SimCLR, but this is portable to any another pre-training methods (all of this has been tested on a jupyter notebook).

First, we have to read the configuration of the model used by SimCLR to train the model:

```
from omegaconf import OmegaConf
from vissl.utils.hydra_config import AttrDict

config = OmegaConf.load("vissl/configs/config/pretrain/simclr/simclr_8node_resnet.yaml")
default_config = OmegaConf.load("vissl/vissl/config/defaults.yaml")
cfg = OmegaConf.merge(config, default_config)
```

We can then transform the configuration to `AttrDict` edit the configuration to specify the features we want to extract, and provide the path to the weights output by SimCLR:

```
cfg = AttrDict(cfg)
cfg.config.MODEL.WEIGHTS_INIT = "path/to/model_final_checkpoint_phase999.torch"
cfg.config.MODEL.FEATURE_EVAL_SETTINGS.EVAL_MODE_ON = True
cfg.config.MODEL.FEATURE_EVAL_SETTINGS.FREEZE_TRUNK_ONLY = True
cfg.config.MODEL.FEATURE_EVAL_SETTINGS.EXTRACT_TRUNK_FEATURES_ONLY = True
cfg.config.MODEL.FEATURE_EVAL_SETTINGS.SHOULD_FLATTEN_FEATS = False
cfg.config.MODEL.FEATURE_EVAL_SETTINGS.LINEAR_EVAL_FEAT_POOL_OPS_MAP = [["res5avg", ["Identity", []]]]
```

Then we can build our model:

```
model = build_model(cfg.config.MODEL, cfg.config.OPTIMIZER)
```

Now, we can load an image and feed it through our encoder:

```
from PIL import Image
import torchvision.transforms as transforms

image = Image.open("/checkpoint/qduval/datasets/food101_vissl/test/apple_pie/1011328.jpg")
pipeline = transforms.Compose([
    transforms.CenterCrop(224),
    transforms.ToTensor(),
])
x = pipeline(image)
features = model(x.unsqueeze(0))
```

The output should be a list with as many entries as features we want to extract (here we just want to extract one, because `LINEAR_EVAL_FEAT_POOL_OPS_MAP` had length one) and each element of the list will contain the features extracted from this level:

```
assert features[0].shape == torch.Size([1, 2048, 1, 1])
```

**Comment by deeptek012** [comment]
@QuentinDuval Thanks for the details! They are really helpful. Only one thing confused me is that I found even the cfg.config.MODEL.WEIGHTS_INIT points to some non-existing path & weight file, the code still runs and you can get the feature embeddings. No "file not found error" ever reported. And I looked at the defaults.yaml or simclr_8node_resnet.yaml, none of them specified default weight files. So I feel really strange here. 

One more comment on the OOM issue. Could we flush out the features as we do inference, rather than holding everything in memory? 

@prigoyal Thanks for the response and looking forward to the new docs and demos.

**Comment by deeptek012** [comment]
@QuentinDuval I also found that the embedding of the same image will change every time we load the same model. Is this a normal behavior?

**Comment by prigoyal** [comment]
> @QuentinDuval Thanks for the details! They are really helpful. Only one thing confused me is that I found even the cfg.config.MODEL.WEIGHTS_INIT points to some non-existing path & weight file, the code still runs and you can get the feature embeddings. No "file not found error" ever reported. And I looked at the defaults.yaml or simclr_8node_resnet.yaml, none of them specified default weight files. So I feel really strange here.

This shouldn't be the case as we specifically check in VISSL that if user has specified a weights_init file, then the file must exist otherwise we throw errors and stop the workflow. See https://github.com/facebookresearch/vissl/blob/master/vissl/trainer/train_task.py#L450-L463

Can you please debug if these checks are working for you? If not, can you please share more details on what the `WEIGHTS_INIT` is set to and what are you observing? We have very recently noticed an issue with a fvcore version that the `PathManager.exists()` check might not be working as expected and for that reason, we are updating the checks in VISSL. 

> 
> One more comment on the OOM issue. Could we flush out the features as we do inference, rather than holding everything in memory?
> 

Yes, we will do this however, please note that this is not a high-pri for us. Almost all use cases I have encountered with different dataset sizes and models work well and the features are normally extracted for the last layer. With that said, the current code allows good scalability (>6 million images). Please let me know if you have a use case in mind where this becomes non-scalable and we will certainly look into prioritizing this request further. 

> @prigoyal Thanks for the response and looking forward to the new docs and demos.

Great! I am curios for your feedback if the answer that Quentin shared above resonates with you on what you expected to be a good demo or docs? if it's missing some information, let us know.

**Comment by prigoyal** [comment]
> @QuentinDuval I also found that the embedding of the same image will change every time we load the same model. Is this a normal behavior?

No. It seems like to me that there is some variability in your model: are you initializing the full model or are there some uninitialized layers?

Also, please note that we can help you debug better if you share more information with us. A single issue can arise due to many reasons and for that reason, we've created templates to gather necessary information. Please follow our templates https://github.com/facebookresearch/vissl/issues/new/choose to open a separate issue and provide as much information as possible.

**Comment by QuentinDuval** [comment]
> @QuentinDuval I also found that the embedding of the same image will change every time we load the same model. Is this a normal behavior?

This is the result of the weights not being correctly initialised in the model: as you saw, the `WEIGHTS_INIT.PARAMS_FILE` is not being used in `build_model` (my bad, I am still new to this code base).

I fixed my example to include the following part, which handles the loading of the model weights:

```
from classy_vision.generic.util import load_checkpoint
from vissl.utils.checkpoint import init_model_from_weights

weights = load_checkpoint(checkpoint_path="/checkpoint/qduval/vissl/model_final_checkpoint_phase999.torch")

init_model_from_weights(
    config=cfg.config,
    model=model,
    state_dict=weights,
    state_dict_key_name="classy_state_dict",
    skip_layers=[],  # Use this if you do not want to load all layers
)
```

@prigoyal I think we can package it in a more straightforward manner (by for instance adding a method in `BaseSSLMultiInputOutputModel` or in the `vissl.util.checkpoint` module).

**Comment by deeptek012** [comment]
Thanks @QuentinDuval, it works! The previous problem is that the model was not initialized. So some random weights got assigned every time. With proper initialization steps, the same model will encode an identical image to the same embedding. And the initialization steps is the one that checks weight file existence.

**Comment by QuentinDuval** [comment]
> Thanks @QuentinDuval, it works! The previous problem is that the model was not initialized. So some random weights got assigned every time. With proper initialization steps, the same model will encode an identical image to the same embedding. And the initialization steps is the one that checks weight file existence.

Excellent! I will create a tutorial for this specific question and we will also look at making it more straightforward in the future.

**Comment by prigoyal** [comment]
closing this issue and @QuentinDuval provided a tutorial. feel free to reach out in case of any follow-ups. Thank you :)

**Comment by yifu-chen-taiwan** [comment]
model = build_model(cfg.config.MODEL, cfg.config.OPTIMIZER)
model.eval() # Add this line and should correctly
