### ISSUE TITLE
 How to run VISSL on video with a Data Transform that chooses a random frame of the video

### ISSUE THREAD

**Issue by pcanas** [facebookresearch/vissl#314]
## ❓ How to run an algorithm on video with a Data Transform that chooses a random frame of the video

Hi, I have been using the library for a while now and I am familiar with its main features.

I know that currently it only supports datasets containing images, but I would like to explore the possibility of using videos and I think I could reuse most of the code from the library while making two changes:
1. Instead of loading an image, it should load a video.
2. The Data Transformation to apply would be selecting a random frame from that video.

From I have seen in the ["Add new Data Transforms" documentation](https://vissl.readthedocs.io/en/v0.1.5/extend_modules/data_transforms.html), point 2 should be feasible by adding a new class for my transform. But I want to get some feedback on how feasible would it be to change the source code of the library to be able to load videos. Could you provide me some feedback about this possibility and some guidance on where is the data loading actually happening so that I could check?

Thank you for your help!

**Comment by prigoyal** [comment]
Hi @pcanas , thank you for reaching out about this. 

VISSL is designed to support loading data from multiple data sources. In order to load the data, VISSL flow is like this: ssl_dataset.py -> disk_dataset.py . The ssl_dataset.py constructs the data_objs depending on what kind of data and data source user is interested in. I think what we will need is something like `disk_video_dataset.py` (Checkout the disk_dataset.py) and it should load the video and return it. The ssl_dataset.py should seamlessly call the new disk_video_dataset.py and construct the data_obj. In the `data/__init__.py`, you should extend the data source map to include the mapping to the new `disk_video_dataset.py`. Hope this helps.
