### ISSUE TITLE
Conversion of model to detectron2 format.

### ISSUE THREAD

**Issue by ashutosh1807** [facebookresearch/vissl#375]
Are there pretrained models available in the format that can be used in detectron2. Or any script for the same.
I want to use the .pkl file for the model.

**Comment by amajee11us** [comment]
I am facing the problem as well. 
Current version of VISSL stores the model in classy_state_dict format and the script provided https://github.com/facebookresearch/vissl/blob/master/extra_scripts/convert_vissl_to_detectron2.py allows us to convert to detectron2 format. But when I use the command with args:
`python convert_model.py --input_model_file model_final_checkpoint_phase999.torch --state_dict_key_name classy_state_dict --output_model model_self.pkl --weights_type numpy `
I am able to generate the .pkl file.

During loading stage in detectron2 I get the following error:
``` 
data = pickle.load(f, encoding="latin1")
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.
```

**Comment by QuentinDuval** [comment]
Hi @amajee11us and @ashutosh1807,

I tried the following command:

```
python extra_scripts/convert_vissl_to_detectron2.py --input_model_file model_final_checkpoint_phase999.torch --state_dict_key_name classy_state_dict --output_model model_self.pkl --weights_type torch
```

The resulting checkpoint can be loaded with `torch.load` but not `pickle.load`. The corresponding file extension to load the file in `detectron2` would be `pyth` and not `pkl`.

I do not think we support the `pkl` format right now (cc: @prigoyal  to confirm).

We could add this support. Just out of curiosity, what is your motivation to use the `pkl` format instead of `pyth` of detectron2?
