### ISSUE TITLE
How to understand the extracted features from VISSL (shape-dimensionality understanding)

### ISSUE THREAD

**Issue by DC95** [facebookresearch/vissl#377]
I have trained my satellite image data set using DC_v2 VISSL, rnet50 in the trunk:

1. The image size is **100x100** pixels:
2. Extracted the features from a single test data image

     **first layer** :["conv1", ["AvgPool2d", [[10, 10], 10, 4]]], output feature shape is (1, 1600)
      and the **last layer**: ["res5avg", ["Identity", []]], output feature shape is (1, 2048)

Maybe I sound stupid, but to understand the extracted feature relation with the original test image, should I reshape them, or am I missing something?

Kindly advice!!

Edit - 
I forgot to write - 
I have checked the options of _MODEL.SHOULD_FLATTEN_FEATS: True/False_ . But the dimensions of the features are the same.

**Comment by QuentinDuval** [comment]
Hi @DC95,

The relation is not very direct and requires a bit of explanation indeed. The ResNet50 architecture is built upon a tower of conv layer and pooling layer that will reduce the size of your feature map (initially 100 times 100) by a factor of 32 reaching "res5" and then average pool and flatten these features at "res5avg".

So at the end you should get (1, 2048) as you noted and the feature map will reduce in size along the way:

```
model = models.resnet50()
model.fc = nn.Identity()
model(torch.randn(size=(1,3,100,100))).shape # shape is (1, 2048)
```

So that is expected. Now, regarding the "conv1" layer:

```
model.conv1(torch.randn(size=(1,3,100,100))).shape # shape is (1, 64, 50, 50)
avg_pool = torch.nn.AvgPool2d([10, 10], 10, 4)
avg_pool(torch.randn(size=(1, 64, 50, 50))).shape # shape is (1, 64, 5, 5)
```

If flattened, this gives the shape (1, 1600) as you observe.

If you want to disable the flattening, you should use the option `config.MODEL.FEATURE_EVAL_SETTINGS.SHOULD_FLATTEN_FEATS=False` and you should get (1, 65, 5, 5) as output.

Tell me if this is working or not for you.

**Comment by DC95** [comment]
Dear @QuentinDuval 

Thank you for the descriptive answer. 
I have tried the option of config.MODEL.FEATURE_EVAL_SETTINGS.SHOULD_FLATTEN_FEATS=False for both the layers and the output is still -  
(1,1600) and (1, 2048). I don't understand why?

I have checked with the middle layers also, but it is throwing flatten outputs.

Kindly find the configuration attached - 
[dcv2_juelich_85x2_FB.txt](https://github.com/facebookresearch/vissl/files/6915645/dcv2_juelich_85x2_FB.txt)

**Comment by QuentinDuval** [comment]
Hi @DC95,

I will have a look at that !

**Comment by QuentinDuval** [comment]
Hi @DC95,

I integrated a fix at 474a1d7c3a1373035249f5324d072b5a7a724d17 which should fix your issue.
Could you try at head?

Thank you,
Quentin

**Comment by DC95** [comment]
Dear @QuentinDuval 

Thank you very much for fixing the bug so quickly and integrating it. It works well now.

We can close this now.

regards,
DC

**Comment by QuentinDuval** [comment]
Awesome ! Thank you for finding the bug :)

Closing the issue :)
